### ISSUE TITLE
empty page strenching up and down

### ISSUE THREAD

**Issue by Tantalus13A98B5F** [yoyurec/logseq-awesome-ui#1]
**Info:**
- OS: Win11 22H2 (22621.521)
- Logseq ver: 0.7.1
- Theme ver: v2.5.3
- [x] ⚠ Do i have issue on SolExt theme with DISABLED my `custom.css`? No never edited that.
- [x] ⚠ Do i have the same on default theme? Not when disabled this plugin, but plugin + default theme will not fix this.

**Description:**
Opening today's journal page, and it will blink like this

![Sep 22nd, 2022 2022-09-22 15-54-30](https://user-images.githubusercontent.com/13904366/191839848-17c2743d-9283-4a03-87f1-adee0934ae4c.gif)

No other page exhibits such behavior. Seems related to `#today-queries`.

**Comment by yoyurec** [comment]
it's Logseq lazy load conflicting somehow...
issue was fixed partially, but still exists  ((

related to: https://github.com/yoyurec/logseq-awesome-ui/issues/2

**Comment by yoyurec** [comment]
@Tantalus13A98B5F does it fixed in the latest version AwesomeStyler?

**Comment by Tantalus13A98B5F** [comment]
Thank you for asking! With AwesomeStyler, it's fixed. However, with AwesomeUI, it's back.

**Comment by yoyurec** [comment]
hmm.... strange. AwesomeUI uses layout positioning which do issue, but it was redone.
will try to fix, but first i need to reproduce...
so i need to open Journals, then click today item. it should no have templated text and backlinks, right?

**Comment by Tantalus13A98B5F** [comment]
you'll need 3 random todo items, then just open the today's page

**Comment by yoyurec** [comment]
why do you have 100% height page? custom css?
check mine:
![image](https://user-images.githubusercontent.com/137919/194330488-2d8c2dcb-2780-4a3b-b1eb-845700a2fd23.png)

**Comment by Tantalus13A98B5F** [comment]
No, I don't use any custom CSS stuff.

Can you try adding 3 more todo items in this page?

**Comment by yoyurec** [comment]
![image](https://user-images.githubusercontent.com/137919/194331029-919946ea-e801-464a-97a8-954ae0d1bf51.png)

**Comment by yoyurec** [comment]
try to:
* uninstall SolExt(if you still have it), uninstall AwesomeUI and uninstal Awesome Styler
* close Logseq
* open Logseq
* install Awesome Styler & Awesome UI again

**Comment by Tantalus13A98B5F** [comment]
okay, before that, my last try; would you create the todo items by `NOW`?

**Comment by Tantalus13A98B5F** [comment]
Well, I have re-installed the plugins and re-opened Logseq, and now I'm having the same problem in an initial graph with just an empty today page lol

**Comment by yoyurec** [comment]
> okay, before that, my last try; would you create the todo items by `NOW`?

same - works ok, not 100% height

**Comment by yoyurec** [comment]
> I have re-installed the plugins

and you have latest **Logseq 0.8.8**?
install latest and do not forget to do Re-Index, cose logseq team updated DB....

![image](https://user-images.githubusercontent.com/137919/194341502-23a9d4ed-808f-4966-baaf-32fa6b6f2d64.png)
**0.7.1** is 4 months old!

**Comment by Tantalus13A98B5F** [comment]
uh I'm so sorry! I thought there would be some kind of auto-update

**Comment by yoyurec** [comment]
ok )))
