### ISSUE TITLE
Idea: hide block properties when collapsed

### ISSUE THREAD

**Issue by alxlg** [yoyurec/logseq-awesome-ui#10]
Have you thought about hiding block properties when the block is collapsed?

**Comment by yoyurec** [comment]
what do you mean?
![ezgif com-gif-maker](https://user-images.githubusercontent.com/137919/197348855-fb0c6116-5e7f-41ef-ad24-7579f804263e.gif)

**Comment by alxlg** [comment]
@yoyurec 

It seems you use a child block to store properties of a block instead of typing them directly in the block... this way you are assigning properties to the child, not to the block itself.

The first block is how I think we are supposed to use block properties and the second is your method, that breaks queries:

![immagine](https://user-images.githubusercontent.com/26327475/197349527-d3c9594f-27c2-4aca-81ba-3c12b335d0a8.png)

**Comment by yoyurec** [comment]
fixed!

**Comment by alxlg** [comment]
@yoyurec 

Great! Would it be possible to show the handle to collapse a block if it has properties but not children?

**Comment by yoyurec** [comment]
it's a question to Logseq https://github.com/logseq/logseq/issues

**Comment by alxlg** [comment]
Done: https://github.com/logseq/logseq/issues/7086

**Comment by alxlg** [comment]
@yoyurec 

FYI it seems hiding properties doesn't work with results of a query like `{{query (property x y)}}`

**Comment by yoyurec** [comment]
> @yoyurec
> 
> FYI it seems hiding properties doesn't work with results of a query like `{{query (property x y)}}`

check latest

**Comment by alxlg** [comment]
@yoyurec looks perfect!
