### ISSUE TITLE
Asking to update even when is updated

### ISSUE THREAD

**Issue by MarceloCajueiro** [yoyurec/logseq-awesome-ui#11]
**Info:**
- OS: macos
- Logseq ver: 0.8.9
- Plugin ver: v1.3.4
- Theme name: Solarized dark

**Description:**
There is a message to update the plugin, even though it's already updated.

**To Reproduce:**
After opening logseq;

**Expected behavior:**
To stop receiving the message after updating the plugin.

**Screenshots**
<img width="405" alt="Screen Shot 2022-10-22 at 15 53 31" src="https://user-images.githubusercontent.com/26076/197357971-d600075e-abb8-498e-a101-098fa2b26e60.png">
<img width="401" alt="Screen Shot 2022-10-22 at 15 53 18" src="https://user-images.githubusercontent.com/26076/197357972-dea73633-cef7-4a65-be1e-fff83848e476.png">

**Comment by yoyurec** [comment]
working on this right now )

**Comment by yoyurec** [comment]
fixed
