### ISSUE TITLE
Ugly properties

### ISSUE THREAD

**Issue by MarceloCajueiro** [yoyurec/logseq-awesome-ui#12]
**Info:**
- OS: macos
- Logseq ver: 0.8.9
- Plugin ver: 1.3.4
- Theme name: solarized dark

**Description:**
The properties are not looking good as used to.

**To Reproduce:**
Just create some properties.

**Expected behavior:**
Looking good properties 🙈

**Screenshots**
<img width="763" alt="image" src="https://user-images.githubusercontent.com/26076/197358071-f73204dd-67b0-4256-820b-6e873206d850.png">

**Comment by yoyurec** [comment]
latest AwesomeStyler?

**Comment by yoyurec** [comment]
and why there are big black borders?
i have no:
![image](https://user-images.githubusercontent.com/137919/197365275-7ca4467f-f61c-4feb-b307-73cb3c89bf49.png)

**Comment by andremann** [comment]
same here. no issue.

**Comment by MarceloCajueiro** [comment]
It worked properly after reinstalling the plugin.
