### ISSUE TITLE
Dropdown menu in kanban is not well-rendered

### ISSUE THREAD

**Issue by andremann** [yoyurec/logseq-awesome-ui#13]
**Info:**
- OS: MacOS
- Logseq ver: 0.8.9
- Plugin ver: 1.3.8
- Theme name: none

- [x] ⚠ Do i have issue with DISABLED my `custom.css`?

**Description:**
If a block is searched within a kanban board, the dropdown menu is cut.

**To Reproduce:**
Create a kanban template and search for a block with `[[...]]`

**Expected behavior:**
The dropdown menu is drawn on top of everything else and it is not cut. 
Maybe a higher z-index would fix?

**Screenshots**
<img width="1026" alt="Screenshot 2022-10-24 at 14 13 02" src="https://user-images.githubusercontent.com/5096918/197525954-584aafd6-4332-487c-a2f0-cb625fdf68b9.png">

**Comment by yoyurec** [comment]
fixed
