### ISSUE TITLE
Make new block bullet respect document mode

### ISSUE THREAD

**Issue by thompson-vii** [yoyurec/logseq-awesome-ui#14]
Document mode is designed for writing long form content without blocks. The new block bullet should instead insert a newline to the block above it when in document mode.

**Comment by yoyurec** [comment]
are you sure this question for plugin, not Logseq?

**Comment by thompson-vii** [comment]
lol sorry i thought the button is from your addon

**Comment by yoyurec** [comment]
no, the plugin just changes it's visibility )
