### ISSUE TITLE
Hope in trans list also can be hidden attributes

### ISSUE THREAD

**Issue by bemofan** [yoyurec/logseq-awesome-ui#15]
![20221025_074057](https://user-images.githubusercontent.com/67182689/197764273-9d6bb1f0-993a-40e3-84f4-cceae579835f.png)
不然 banner 看起来太长了
thank you very much,This is a very great plugin

**Comment by yoyurec** [comment]
not clear...
Do you have an issue with hiding props that are not in English?

**Comment by yoyurec** [comment]
@bemofan ?
not clear

**Comment by bemofan** [comment]
![20221028_045140](https://user-images.githubusercontent.com/67182689/198546562-19d23986-cd27-40b5-bcb0-dc35c6a8d663.png)
Hidden attributes in the chain

**Comment by yoyurec** [comment]
1. this is default Logseq behavior - to show props block if the related word was found there
2. if you want to hide `banner`, then it's an issue for https://github.com/yoyurec/logseq-banners-plugin
3. looks like you are using `banner` wrong - it should be in quotes `"..."` - so Logseq will not show it as an image

**Comment by yoyurec** [comment]
@bemofan  check latest release, props also hides on `.block-properties`, not only on `.page-properties`
PS: with small limitation - no "live listener" on edit-view mode as on page props. block props will be hidden on page scroll/load/reload...
