### ISSUE TITLE
Tabs + Awesome UI plugin conflict - prevents dragging LogSeq window

### ISSUE THREAD

**Issue by ahpatel** [yoyurec/logseq-awesome-ui#18]
**Info:**
* OS: Mac OS 12.6.1
* Logseq ver: 0.8.9
* Plugin ver: 1.3.9 (though issue occured in previous builds as well)
* Theme name: Awesome Styler 3.1.8

[x] ⚠ Do i have issue with DISABLED my `custom.css`? Yes, issue occurs with a blank custom.css file

**Description:**
Using Awesome UI and Tabs together often results in the inability to move/drag the LogSeq window.

**To Reproduce:**
1. Enable Awesome UI and Tabs plugins.
2. Open multiple tabs in LogSeq
3. Pin a tab (double click on a tab title)
4. Hover over the title bar with your mouse and try to drag the window
NOTE: there are a few more common use cases of just opening tabs that also causes this issue, but I haven't found a pattern I can consistently reproduce yet.  That said, I think the issue shown with the pin/unpin tab scenario above is likely to give us insight to the root cause.

**Expected behavior:**
1. LogSeq window should drag with the mouse.

**Workarounds/Additional Notes**
1. Resizing the LogSeq window and then dragging it consistently resolves it, though only temporarily
2. When I disable tabs plugin, I have never had Awesome UI prevent a drag.  Meaning, it's specifically appears to be an issue between Tabs and Awesome UI (and not Awesome UI and other plugins).

**Recording of the issue**
* https://user-images.githubusercontent.com/9514136/198145277-a2100d47-50b0-4d6a-87bb-c4683b1a0d1d.mov

**Comment by yoyurec** [comment]
https://github.com/pengx17/logseq-plugin-tabs/pull/63

**Comment by yoyurec** [comment]
@ahpatel  test the latest Tabs plugin

**Comment by ahpatel** [comment]
yes, appears to be resolved!
