### ISSUE TITLE
Make an optional centered search bar

### ISSUE THREAD

**Issue by cnut1648** [yoyurec/logseq-awesome-ui#20]
**Idea**
Currently the search bar behaves like that in a web browser, which looks really good. But sometimes users can have a lot of plugins and those plugins will occupy space in the top bar so that the search bar is very small (please see my screenshot below). I wonder if it's possible to dynamically switch back to the centered search bar like vanilla logseq if the window size is too small, or if it's not possible, expose an option so that users can use the vanilla logseq search.

Thank you.

**Screenshots**
This is the search bar if the window size is small
![image](https://user-images.githubusercontent.com/37067883/198908027-c05db58c-df87-4964-b235-96ebb570caf4.png)
and search becomes
![image](https://user-images.githubusercontent.com/37067883/198908040-ba9fc64c-3df1-4ef1-bdd3-1f270270b6f1.png)

**Attach files**
Add (via drag-n-drop) .zip with `.md` files if it help me with experiments

**Comment by yoyurec** [comment]
> if the window size is too small

how much small? in px?
i can set min-width to search

**Comment by yoyurec** [comment]
why make it optional if it can be just smarter?! ))
check the latest release

![image](https://user-images.githubusercontent.com/137919/199150825-53c9514b-783d-4032-876e-960420192058.png)

**Comment by cnut1648** [comment]
@yoyurec wow, awesome feature!!! Thanks a lot this looks really great!

**Comment by yoyurec** [comment]
@cnut1648 now also optional!
check latest **v1.6.x**

![search](https://user-images.githubusercontent.com/137919/217100709-5b758c89-f4c7-46b4-95df-f62de20a02df.png)
