### ISSUE TITLE
property icons display wrong when set property-pages false

### ISSUE THREAD

**Issue by zhydong258** [yoyurec/logseq-awesome-ui#21]
Info:
OS: win11
Logseq ver: 0.8.9
Plugin ver: 1.3.14
Theme name:  Default Dark theme or bonofix dark theme

Description:
when set `property-pages/enable? false` in config.edu, property icons display wrong in view mode.
But icons display well in edit mode.

To Reproduce:

Screenshots:
![image](https://user-images.githubusercontent.com/1166608/198978429-38e9d02e-4c70-4c9d-a6ba-57b7da738d13.png)
![image](https://user-images.githubusercontent.com/1166608/198978497-3d93b2d0-9373-4d87-a1fb-a5a950e66d8a.png)

Hope you can fix it, thank you very much.

**Comment by yoyurec** [comment]
i can fix it, but with limitations ((
prop-key as link has additional info, so i can style icon, according to key text.
if key is not a link - i can read info only from prop value - and this will be just 'text, page link, external link'
![image](https://user-images.githubusercontent.com/137919/199104203-c78fcfe3-0c3e-435e-814c-299a4993fcef.png)
