### ISSUE TITLE
Blockquote does not work with another tag in the same block

### ISSUE THREAD

**Issue by drdanielbender** [yoyurec/logseq-awesome-ui#22]
**Info:**
- OS: Windows
- Logseq ver: 0.8.10
- Plugin ver: 1.3.20
- Theme name:

- [ ] ⚠ Do i have issue with DISABLED my `custom.css`?

**Description:**
The blockquote only works if there is no other tag in the same block. Adding the #quote tag multiple times is fine.

**To Reproduce:**
Add another tag to a block with the tag #quote

**Expected behavior:**
 Even with another tag besides #quote, the blockquote should be visualized.

**Screenshots**
![image](https://user-images.githubusercontent.com/113003545/199601977-12c18428-9f20-4086-8c7e-d488eb5d3f6d.png)
![image](https://user-images.githubusercontent.com/113003545/199602062-89271cec-fb03-4e6f-bfe1-14c55d59704f.png)
![image](https://user-images.githubusercontent.com/113003545/199602230-386b2f9f-772c-4e89-b553-02c285a6763d.png)

**Comment by yoyurec** [comment]
fixed in latest release
