### ISSUE TITLE
Property "show default icons in left sidebar" not working

### ISSUE THREAD

**Issue by andremann** [yoyurec/logseq-awesome-ui#23]
**Info:**
- OS: MacOS Ventura
- Logseq ver: 0.8.10
- Plugin ver: 1.3.20
- Theme name: Awesome Styler

- [x] ⚠ Do i have issue with DISABLED my `custom.css`?

**Description:**
The "show default icons in left sidebar" doesn't affect logseq.

**To Reproduce:**
 Toggle the property, no changes. Even after restart.

**Expected behavior:**
 The property makes appear/disappear default icons.

**Comment by yoyurec** [comment]
are you using "Awesome Links" also?

**Comment by andremann** [comment]
Yep. You mean the other plugin overrides the checkbox with the default icons and colours?

**Comment by yoyurec** [comment]
AwLinks owerrides AwUI plugin...
BUT! you can set your own icon )

![image](https://user-images.githubusercontent.com/137919/199711789-2910a2d0-04ad-488b-b044-164270f17e16.png)
