### ISSUE TITLE
"#quote" makes the vertical line of the list disappear 

### ISSUE THREAD

**Issue by jimmy909090** [yoyurec/logseq-awesome-ui#24]
![image](https://user-images.githubusercontent.com/113656415/200009933-a99e6631-d22f-48f9-a936-87409f37034d.png)

**Comment by yoyurec** [comment]
it was done espicially )
think i should roll it back?

**Comment by yoyurec** [comment]
i was trying to target this one
![image](https://user-images.githubusercontent.com/137919/200011498-74496b0c-1c01-4248-9625-409b006f3823.png)

but it hides more )

**Comment by jimmy909090** [comment]
> i was trying to target this one ![image](https://user-images.githubusercontent.com/137919/200011498-74496b0c-1c01-4248-9625-409b006f3823.png)
> 
> but it hides more )

I think it's solving a small aesthetic problem by creating a larger aesthetic problem.

This really looks too ugly and strange:

![image](https://user-images.githubusercontent.com/113656415/200016930-5aed1f57-8f0f-4302-862b-3b23433f4aa1.png)

**Comment by yoyurec** [comment]
fixed, check latest release
