### ISSUE TITLE
When changed main font size by google fonts plugin, the page properties icon size is mismatch

### ISSUE THREAD

**Issue by hh23485** [yoyurec/logseq-awesome-ui#25]
**Info:**
- OS: win
- Logseq ver: 0.8.10
- Plugin ver: 1.4.10
- Theme name: dev

- [ ] ⚠ Do i have issue with DISABLED my `custom.css`?

**Description:**
When I changed the font size through google fonts plugin, the icon of page property is mismatch

**To Reproduce:**
 1. Install `Google fonts` plugin
 2. Set main font size to 1.25em
 3. go to any page, try to edit the page properties
![image](https://user-images.githubusercontent.com/14577931/200812050-b8453687-1c89-47c8-94b2-18224dafa160.png)

**Expected behavior:**
 The image icon size should the same with font size

**Screenshots**
![image](https://user-images.githubusercontent.com/14577931/200812132-b146cce6-ef04-4d02-a377-f1058465e52d.png)

**Attach files**
Nope

**Comment by yoyurec** [comment]
check latest release!
