### ISSUE TITLE
Responsive Search Bar is great, but where is the window dragging affordance?

### ISSUE THREAD

**Issue by jonahgoldsaito** [yoyurec/logseq-awesome-ui#26]
**Idea**
I really like the concept of the full-width, responsive Search bar, but now I can't find a clear affordance for how to move my Logseq window around. It quite possibly exists, but I'm just not seeing it. A clear affordance would be great, and if not, I'd love to turn off the Search Bar in the settings since I really always just hit ⌘K to search reflexively, and never click to search.

**Comment by yoyurec** [comment]
macOS?

**Comment by jonahgoldsaito** [comment]
Yes, MacOS.

There is a tiny strip of pixels on the top edge, I realize.

Perhaps if hovering over that strip changed the CSS cursor to the movement
curator it would be clearer.

I must move my window more than most people (like to the right of a video
chat or something:)

**Comment by yoyurec** [comment]
> Yes, MacOS.

why i should guess it if issue template exists for it? 🤔

![image](https://user-images.githubusercontent.com/137919/201382217-164ee04f-2f36-4525-a8f5-95a6966ceabd.png)

**Comment by yoyurec** [comment]
> Perhaps if hovering over that strip changed the CSS cursor to the movement
curator it would be clearer.

need to test how it looks... or maybe create a whole search bar draggable...

are you using Tabs plugin? there is a bigger drag area!

![image](https://user-images.githubusercontent.com/137919/201383027-67141921-408f-4bd9-a917-7f77b8a0695a.png)

**Comment by jonahgoldsaito** [comment]
I hadn't updated Tabs in a while. It actually disappeared visibly when I installed Awesome UI. When I just updated it, it reappeared and introduced a large additional area for both tabs and dragging as you suggested. But that's only a solution for people who you Tabs.

**Comment by yoyurec** [comment]
for ppl without Tabs you can drag via big search field on header!

**Comment by yoyurec** [comment]
@jonahgoldsaito now wide search is optional!
check latest v.1.6.x

![search](https://user-images.githubusercontent.com/137919/217100815-900347d7-a775-4a3c-b16a-8f49aaccc021.png)
