### ISSUE TITLE
Find text window does not display

### ISSUE THREAD

**Issue by cleanclothes-pi** [yoyurec/logseq-awesome-ui#27]
**Info:**
- OS: MacOS
- Logseq ver: 0.8.10
- Plugin ver: 1.4.11
- Theme name: Awesome Styler (but bug also occurs when using default and other themes)

**Description:**
When pressing command+F, the 'find text in page' pop-up window does not display. However, if I type some letters after pressing the shortcut, the words are still highlighted (see screenshot). This means the function still works, it's just that the find window is not displayed properly.

**To Reproduce:**
Invoke 'find text in page' command, then type in a few letters.

**Expected behavior:**
Display the 'find text' pop-up window when pressing command+F.

**Screenshots**
![2022-11-12_21-07](https://user-images.githubusercontent.com/58788103/201502283-b7f5cbda-eab1-4963-9759-2768ccafa1a3.png)

**Comment by ecodiv** [comment]
Same here, enabling AwesomeUI makes the search box almost completely disappear. I guess a CSS matter of redefining the position of that search popup, see below.

![image](https://user-images.githubusercontent.com/7816789/203032006-c610644f-c239-422a-8cbb-6bf237098451.png)

**Comment by TomazWang** [comment]
Same here, sorry I created a duplicated issue (#30)

**Comment by TomazWang** [comment]
Update, I found the `#search-in-page` element is blocked by header
![image](https://user-images.githubusercontent.com/7992586/206333963-dd56bd33-cdae-462d-a6b2-4238664bdc27.png)

**Comment by TomazWang** [comment]
I found that disable `z-index` of `#main-content-container` will fix this issue
![CleanShot 2022-12-08 at 10 05 38](https://user-images.githubusercontent.com/7992586/206338829-840188d7-aec5-43f0-aa5e-8322a9041718.gif)

**Comment by williamlwclwc** [comment]
A workaround by adding this: `#search-in-page{ top: 6rem; }` to `custom.css` seems to work for me. 
<img width="434" alt="image" src="https://user-images.githubusercontent.com/30679848/214990978-43c2bb06-b247-4f76-8ee4-56d7deaedb4d.png">

**Comment by artemith** [comment]
> A workaround by adding this: `#search-in-page{ top: 6rem; }` to `custom.css` seems to work for me. 
> <img width="434" alt="image" src="https://user-images.githubusercontent.com/30679848/214990978-43c2bb06-b247-4f76-8ee4-56d7deaedb4d.png">
> 

Thanks, it works for me too!

**Comment by yoyurec** [comment]
fixed! https://github.com/yoyurec/logseq-awesome-ui/commit/130af5908361a3da038aaae26c50001c5555467c

ps: sorry for late response, there are fucking russians doing war in Ukraine 🤬
