### ISSUE TITLE
Search Box on Mac (cmd + f) not working

### ISSUE THREAD

**Issue by TomazWang** [yoyurec/logseq-awesome-ui#30]
**Info:**
- OS: `macOS 12.4`
- Logseq ver: `0.8.12`
- Plugin ver: `1.4.12`
- Theme name: `Awesome Styler Dark`

- [x] ⚠ Do i have issue with DISABLED my `custom.css`?

**Description:**

`Search in page` function not working when Awesome UI plugin enabled.

**To Reproduce:**
 ...

- Enable `Awesome UI` >  press `cmd`+`f` in any page > nothing happens
- Disable `Awesome UI` > press `cmd`+`f` in a page > search box appears

**Expected behavior:**

- search box should show and function normally (as pure logseq)

**Screenshots**
![CleanShot 2022-12-08 at 09 20 44](https://user-images.githubusercontent.com/7992586/206333134-08e64f3f-5875-43c9-85be-28a8ec040ce5.gif)
help explain your problem.

**Attach files**
- screenshot gif above.

**Comment by TomazWang** [comment]
Duplicate with #27

**Comment by yoyurec** [comment]
fixed! https://github.com/yoyurec/logseq-awesome-ui/commit/130af5908361a3da038aaae26c50001c5555467c
