### ISSUE TITLE
Incompatibility with whiteboard

### ISSUE THREAD

**Issue by fr0der1c** [yoyurec/logseq-awesome-ui#31]
**Info:**
- OS: macOS
- Logseq ver: 0.8.14
- Plugin ver: 1.4.12
- Theme name: no theme

**Description:**
The whiteboard feature of Logseq becomes Beta in 0.8.14. However, with Awesome UI installed, I'm unable to change the title of the whiteboard.

With Awesome UI disabled:
<img width="1637" alt="截屏2022-12-21 12 48 28" src="https://user-images.githubusercontent.com/16500161/208824054-136cb9e6-1b8d-45b6-b5f0-fbdb06a176b9.png">

With Awesome UI enabled:
<img width="1637" alt="截屏2022-12-21 12 49 08" src="https://user-images.githubusercontent.com/16500161/208824109-3e0edcc1-51e8-45d6-a134-bc8404fec07f.png">

**To Reproduce:**
 Use 0.8.14 to create a whiteboard with a Backer/Sponsor account of Logseq.

**Expected behavior:**
 Being able to change the whiteboard title.

**Comment by lss6378** [comment]
> **Info:**
> 
>     * OS: macOS
> 
>     * Logseq ver: 0.8.14
> 
>     * Plugin ver: 1.4.12
> 
>     * Theme name: no theme
> 
> 
> **Description:** The whiteboard feature of Logseq becomes Beta in 0.8.14. However, with Awesome UI installed, I'm unable to change the title of the whiteboard.
> 
> With Awesome UI disabled: <img alt="截屏2022-12-21 12 48 28" width="1637" src="https://user-images.githubusercontent.com/16500161/208824054-136cb9e6-1b8d-45b6-b5f0-fbdb06a176b9.png">
> 
> With Awesome UI enabled: <img alt="截屏2022-12-21 12 49 08" width="1637" src="https://user-images.githubusercontent.com/16500161/208824109-3e0edcc1-51e8-45d6-a134-bc8404fec07f.png">
> 
> **To Reproduce:** Use 0.8.14 to create a whiteboard with a Backer/Sponsor account of Logseq.
> 
> **Expected behavior:** Being able to change the whiteboard title.

same for me:
```
OS: Window10 
Logseq ver: 0.8.14
Plugin ver: 1.4.12
```

**Comment by yoyurec** [comment]
@lss6378  @fr0der1c 
fixed in latest!
