### ISSUE TITLE
search box not visible in `logseq/config.edn`

### ISSUE THREAD

**Issue by avelino** [yoyurec/logseq-awesome-ui#33]
**Info:**
- OS: macOS
- Logseq ver: 0.8.16
- Plugin ver: v1.4.12
- Theme name: Awesome Styler Light

- [x] ⚠ Do i have issue with DISABLED my `custom.css`?

**Description:**
the search field (find) is not visible on the edit configuration page

**To Reproduce:**
1. open settings
2. click edit `config.edn`
3. `cmd + f`

**Expected behavior:**
make the search field visible, not hidden in the top bar

**Screenshots**
<img width="759" alt="Screenshot 2023-01-23 at 09 10 24" src="https://user-images.githubusercontent.com/31996/214037244-872d9268-4b3c-469b-8dfe-9fe79f63856f.png">

**Comment by zheladev** [comment]
As a temporary workaround for this issue, you can add the following css rule to your custom.css file:
```css
#search-in-page {
    margin-top: 60px !important;
}
```

**Comment by yoyurec** [comment]
fixed https://github.com/yoyurec/logseq-awesome-ui/commit/130af5908361a3da038aaae26c50001c5555467c
