### ISSUE TITLE
UI inconsistencies when using with Focus Mode plugin

### ISSUE THREAD

**Issue by senntore** [yoyurec/logseq-awesome-ui#34]
**Info:**
- OS: Pop!_OS 22.04
- Logseq ver: 0.8.16
- Plugin ver: v1.4.12
  
**Description:**
When hiding top bar using the Focus Mode plugin, the top part of left & right side bars seems to disappear

**To Reproduce:**
1. Install Focus Mode plugin from the Marketplace.
2. Check "Toggle Top Bar" in that plugin's settings.
3. Enable Focus Mode.
4. Toggle Left/Right Side bar.
Screenshot: 
With both Awesome UI & Awesome Styler
![Screenshot from 2023-01-24 16-16-27](https://user-images.githubusercontent.com/58325574/214274108-34d3dbc5-6582-431b-8a04-5412b2a1752c.png)

**Expected behavior:**
In default theme & with Awesome Styler, this is how the top part of sidebars look
Screenshot:
![Screenshot from 2023-01-24 16-16-06](https://user-images.githubusercontent.com/58325574/214274314-627ae572-e921-4751-8b26-1f11e6931e08.png)

Notes: This might be intended since the top bar in awesome ui covers all of the top portion but I think there can be improvement similar to how top part of left side bar behaves in default theme.

**Comment by yoyurec** [comment]
For intercating with other plugins, AwseomeUI needs to know that some "mode" enabled + have possibility to rewrite author styles.
Most used solution - set *a flag* class (for ex. "`is-focused-mode`) to `<body>`.

But that's question for **Focus Mode plugin** developer to rework functionality and rewrite few styles (`.is-focused-mode #head {opacity: 0;}`, etc...) or smbody else can do PR.

or you need own `custom.css` rules that fits your needs...

**Comment by yoyurec** [comment]
also layout is differrs - FosusMode hide default Logseq header. In AwesomeUi header = top part of left sidebar + logseq header + top part of right sidebar... so they are not compatible
