### ISSUE TITLE
Arrange the back and forward button to not overlap with the API server

### ISSUE THREAD

**Issue by hdansou** [yoyurec/logseq-awesome-ui#37]
**Info:**
- OS: macOS
- Logseq ver:
- Plugin ver:
- Theme name:

- [ ] ⚠ Do i have issue with DISABLED my `custom.css`?

**Description:**
 There is a minor update needed on Awesome UI, since the release of the HTTP API server. Check this screenshot
Image
![image](https://user-images.githubusercontent.com/536716/216853403-90300332-40b9-4483-98dd-721b20736313.png)

**To Reproduce:**
 Enable the API server

**Expected behavior:**
 the API server icons should not overlap with the the back button

**Screenshots**

**Attach files**
Add (via drag-n-drop) .zip with `.md` files (if it needs) to help with bugfixind

**Comment by yoyurec** [comment]
BTW, what it for and how it works? any docs? info?

**Comment by yoyurec** [comment]
fixed in v.1.5.1!
