### ISSUE TITLE
Is there a way to disable the wide responsive search?

### ISSUE THREAD

**Issue by mhp92** [yoyurec/logseq-awesome-ui#38]
**Idea**
I really like the plug in. The only thing that annoys me is the Wide responsive search. I want the default.

**Screenshots**
Add some pictures to get the idea if needed

**Attach files**
Add (via drag-n-drop) .zip with `.md` files if it help me with experiments

**Comment by yoyurec** [comment]
i think it's possible
plus more ppl asking about this...

there was a small button and a small popup.
do you want:
* **wide button + small popup**
*  or **small button** (with lot of empty space in header 🙄 - as header/sidebars will stay reworked anyway) **+ small popup**?

![image](https://user-images.githubusercontent.com/137919/216966229-8189d963-d04d-452b-b864-a37da419274c.png)

**Comment by yoyurec** [comment]
in case "wide button + small popup" top left corners will not be visually aligned as before ((
is it ok?

![image](https://user-images.githubusercontent.com/137919/216967706-50df781b-5c08-49cf-bf2e-5dc40ab3eee3.png)

**Comment by mhp92** [comment]
I just want it to be like the default, because it's clean, gives me maximum space, and is not distracting.

<img width="1338" alt="Screenshot 2023-02-06 at 13 11 18" src="https://user-images.githubusercontent.com/43569943/216968260-04c24a12-23c5-47a7-ab32-cc9c0980f3ab.png">

**Comment by yoyurec** [comment]
Rolling search button back to defaults also affects other UI elements... what about nav arrows?

is it OK to be on left side as on AwesomeUI
![image](https://user-images.githubusercontent.com/137919/217046552-2b944aa4-c2c1-40b2-8a30-3685ea961563.png)

OR on right side as Logseq default?
![image](https://user-images.githubusercontent.com/137919/217046456-48316e21-1c97-4195-a4c5-1a959df86d28.png)

**Comment by mhp92** [comment]
Yes that would be also fine. Main Thing is that it's clean and also in the same row as the red, orange and green buttons (not sure how you call it).

**Comment by yoyurec** [comment]
> Yes that would be also fine

there were 2 options)) OR OR ) which one?

**Comment by mhp92** [comment]
I am totally fine with both options left or right doesn't matter.

**Comment by yoyurec** [comment]
now wide search is optional!
check latest **v1.6.x**

![search](https://user-images.githubusercontent.com/137919/217100950-e88e7665-b0a2-4a09-a199-082fadef4505.png)
