### ISSUE TITLE
Switching Tabs produce shows an empty Calendar

### ISSUE THREAD

**Issue by ryepesg** [yoyurec/logseq-awesome-ui#39]
**Info:**
- OS: MacOS
- Logseq ver: 0.8.16 
- Plugin ver: v1.6.8
- Theme name: None

- [x] ⚠ Do i have issue with DISABLED my `custom.css`?

**Description:**

The Calendar page shows an empty page instead of the Agenda Dashboard

**To Reproduce:**
 
1. Install the Agenda plugin v2.13.0 and the Tabs plugin v1.18.1
2. Open more than one Tab
3. Use the Calendar button to open the Agenda Calendar in one of the Tabs
4. Use `CTRL + TAB` to switch tabs until you reach the Calendar one that has empty content

**Expected behavior:**

Open the Agenda Calendar as if I had used the Calendar button instead of switching tabs 

**Screenshots**

<img width="508" alt="image" src="https://user-images.githubusercontent.com/10557463/217461348-aa6c73e3-618c-4110-ac4b-b3c211af079c.png">

**Comment by yoyurec** [comment]
* Clicking "Calendar" button doing 2 things - opens the page (`calendar.md`) +doing click on Agenda plugin button and shows it as an overlay.
* When you close **Agenda** (via it's a power button `(|)` on the bottom left), the overlay closes, "Calendar" page stays.
* In case you are using **Tabs** plugin, on switching tabs content reloads. And when you reach Calendar - content shows the page that tab points to - `calendar.md`.

BTW, as AwesomeUI just mimics Agenda plugin button, it works the same - on page switch it closes popup. One difference - in original popup, you have no possibility to switch, b'cose it full screen ))

Dunno what to do. I could try to detect page switching and when it's a Calendar - show Agenda popup again... but what if you actually want to open `calendar.md` for editing??? For ex. mine:
![image](https://user-images.githubusercontent.com/137919/217519625-37301c9e-f209-4df1-879d-18fa60de5c0e.png)

It would be inaccessible. At least till i close Agenda popup...

Need to measure how often 2 cases appears - editing `calendar.md` or switching tabs )))

Is it clear enough? What do you think about described issue\limitations?

**Comment by ryepesg** [comment]
Thanks for the explanation, it is very clear indeed. Maybe one way to solve it could be using a hidden page like `.v.calendar.md`, in the same way as LogTools use the `.v-kanban` to avoid collisions with "kanban" which is a name that user probably using already.

**Comment by yoyurec** [comment]
nice idea! need to test )

**Comment by yoyurec** [comment]
check latest!

**Comment by yoyurec** [comment]
and add to `calendar.___.md` props )
```
icon:: 📆
```

**Comment by ryepesg** [comment]
Tested, it works great, thank you @yoyurec !

**Comment by yoyurec** [comment]
@ryepesg tabs switching https://github.com/yoyurec/logseq-awesome-ui/issues/42 fixed!

**Comment by yoyurec** [comment]
`calendar` page is back. empty `calendar.` was not good idea for those who have no Agenda plugin...

**Comment by ryepesg** [comment]
Thank you very much for the update @yoyurec. I tested it and indeed it started to work at the beginning, but then it stopped working after changing a few tabs and the Agenda overlay doesn't seem to follow the size for the window:
Steps to reproduce:
1. Click the "Calendar" button
2. Press the shortcut to change tab (observe the overlay is shown in the wrong tab instead of the calendar tab):
<img width="521" alt="image" src="https://user-images.githubusercontent.com/10557463/218899750-b2edddb5-e616-4f90-919c-5eece8e044bc.png">
3. Close the left panel and observe the overlay doesn't cover the page:
<img width="511" alt="image" src="https://user-images.githubusercontent.com/10557463/218899974-a7df605d-0167-4645-8405-a7f6ed7959a6.png">

Exception:
<img width="540" alt="image" src="https://user-images.githubusercontent.com/10557463/218900134-b8ba7c21-2b27-4dc1-9c84-fee35857de39.png">

**Comment by yoyurec** [comment]
right sidebar live-resize not supported and not planned. reading sidebars width on Calendar open/close/switching **only** (need to be polished...)!

**Comment by yoyurec** [comment]
fixed!
(no resize on right sidebar resize)
