### ISSUE TITLE
[Request] Built-in bullet threading

### ISSUE THREAD

**Issue by chiahsien** [yoyurec/logseq-awesome-ui#4]
**Idea**
[Bullet threading](https://github.com/pengx17/logseq-plugin-bullet-threading) is a useful feature, and I'd like to see it in Awesome UI so that I don't have to install an extra plugin for such a feature.

**Comment by yoyurec** [comment]
"Bullet threading" is complicated plugin i have no wish to support and develop...
Also i will not include plugins (especially not mine) to Awesome UI, cose i just extracted 3 from SolExt )))
Idea is to have more atomic features...

So, sorry, but no
