### ISSUE TITLE
Empty area keep existing on the top left

### ISSUE THREAD

**Issue by Gitbreast** [yoyurec/logseq-awesome-ui#40]
**Info:**
- OS: MacOS
- Logseq ver: 0.8.17
- Plugin ver: 1.6.11
- Theme name: Default

- [x] ⚠ Do i have issue with DISABLED my `custom.css`?

**Description:**
An empty area keeps existing on the top left upon the graph name. It still exists after reloading or reopening Logseq.

**To Reproduce:**
No need.

**Expected behavior:**
No empty area.

**Screenshots**
<img width="155" alt="image" src="https://user-images.githubusercontent.com/96460796/217713870-a1f4fcf9-e350-4524-a8c6-b0c71b676178.png">

**Attach files**
Add (via drag-n-drop) .zip with `.md` files (if it needs) to help with bugfixind

**Comment by ryepesg** [comment]
Hi @Gitbreast, can you please provide more details about why is this an issue and not just an opinion about style? Maybe a screenshot showing more context to understand why it doesn't matches your expectation? Thanks,

**Comment by Gitbreast** [comment]
> Hi @Gitbreast, can you please provide more details about why is this an issue and not just an opinion about style? Maybe a screenshot showing more context to understand why it doesn't matches your expectation? Thanks,

<img width="1468" alt="image" src="https://user-images.githubusercontent.com/96460796/217841888-94375196-b1ed-427a-b029-d74d45f0735e.png">
Here. My point is why a new empty area show up upon the graph name.
<img width="92" alt="image" src="https://user-images.githubusercontent.com/96460796/217844158-3db2ca83-2ac9-4a53-8a15-7024fb4b6c34.png">
Is this a new update about style? But I couldn't find any info about this. It never like this before. Thanks.

**Comment by yoyurec** [comment]
fixed!
