### ISSUE TITLE
Part of UI hidden by top bar

### ISSUE THREAD

**Issue by screenfluent** [yoyurec/logseq-awesome-ui#43]
**Info:**
- OS: macOS 12.6.3
- Logseq ver: 0.8.17
- Plugin ver: 1.6.13
- Theme name: None

- [ ] ⚠ Do i have issue with DISABLED my `custom.css`?

**Description:**
With clean Logseq (no other plugins nor themes) part of UI is hidden by top bar.

**To Reproduce:**
 Turn plugin on. No changes of settings needed.

**Expected behavior:**
 UI not covered by the top bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/116732045/218244365-244f6dbf-f935-4db9-a180-dc005300c086.png)

**Attach files**
Add (via drag-n-drop) .zip with `.md` files (if it needs) to help with bugfixind

**Comment by yoyurec** [comment]
this is after the plugin install?
reloading logseq help? or it appear again?

**Comment by screenfluent** [comment]
Yes, I've returned to Logseq after several weeks of not using it. I installed the plugin and it appeared as it does in the screenshot. I tried using CMD+R and then quitting and reopening the app, but neither solution worked.

**Comment by yoyurec** [comment]
oh ((
will try to fix....

**Comment by karkraeg** [comment]
Same here, with empty custom.css, latest Logseq Version (0.8.17)

**Comment by yoyurec** [comment]
fixed!
