### ISSUE TITLE
Whiteboards broken

### ISSUE THREAD

**Issue by screenfluent** [yoyurec/logseq-awesome-ui#44]
**Info:**
- OS: macOS 12.6.3
- Logseq ver: 0.8.17
- Plugin ver: 1.6.13
- Theme name: None

- [ ] ⚠ Do i have issue with DISABLED my `custom.css`?

**Description:**
Plugin is breaking Whiteboards. I can see the list of all boards but when click on any or newly created UI elements are missing and no content.

**To Reproduce:**
 Activate the plugin with default settings.

**Expected behavior:**
Working Whiteboards. :)

**Screenshots**
![image](https://user-images.githubusercontent.com/116732045/218245046-af253190-b768-4ab4-8695-a57d7f75b1d1.png)
![image](https://user-images.githubusercontent.com/116732045/218244874-3fbf9056-6245-4689-91e6-599ea5bdc27e.png)

**Attach files**
Add (via drag-n-drop) .zip with `.md` files (if it needs) to help with bugfixind

**Comment by yoyurec** [comment]
only on fresh released Logseq 0.8.17? 0.8.16 was ok?

**Comment by yoyurec** [comment]
i think it's same bug https://github.com/yoyurec/logseq-awesome-ui/issues/44

**Comment by screenfluent** [comment]
Unfortunately, I am not aware if it worked OK with previous versions of Logseq because I had not installed it previously.

**Comment by yoyurec** [comment]
fixed!
