### ISSUE TITLE
3.3.3 update cuts off top of page and left menu

### ISSUE THREAD

**Issue by lsdjr72** [yoyurec/logseq-awesome-ui#46]
**Info:**
- OS: Mac OS 13.1
- Logseq ver: 0.8.17
- Plugin ver: 3.3.3
- [ ] ⚠ Do i have issue with DISABLED my `custom.css`? NO
- [ ] ⚠ Do i have the same on default theme? NO

**Description:**
Updating to 3.3.3. results in the left menu being cut off at the top (to the point you can't get to your graph menu). Also cuts off top of pages

**To Reproduce:**
 ...

**Expected behavior:**
 ...

**Screenshots**
<img width="1419" alt="Screenshot 2023-02-10 at 10 47 58 PM" src="https://user-images.githubusercontent.com/48802344/218240766-9ebf0577-9956-4224-b897-88e55573fdc9.png">

**Attach files**
Add (via drag-n-drop) .zip with `.md` files (if it needs) to help with bugfixind

**Comment by yoyurec** [comment]
it's AwesomeUi i think...

have you reloaded/restarted Logseq?

**Comment by yoyurec** [comment]
fixed!
