### ISSUE TITLE
Marker colors don't change without forcing a refresh to `custom.css`

### ISSUE THREAD

**Issue by Zachu** [yoyurec/logseq-awesome-ui#47]
**Info:**
- OS: Linux Pop!_OS 22.04
- Logseq ver: 0.8.17
- Plugin ver: 1.7.0
- Theme name: Slightly modified mIA

- [x] ~~⚠ Do i have issue with DISABLED my `custom.css`?~~
  - Doesn't apply

**Description:**
Overwriting `awUI-marker` values from `custom.css` `:root` block sort of doesn't work. It works if you trigger a change (or just save the file without changes). But if you reload Logseq by CTRL + R or just reopen it the changes are not visible.

**To Reproduce:**

Having following block

```md
- ## Tasks
	- TODO Todo
	- DOING Doing
	- NOW Now
	- DONE Done
	- WAITING Waiting
	- LATER Later
	- CANCELLED Cancelled
```

And `custom.css`
```css
:root {
    --awUI-marker-waiting: rgb(255, 0, 255);
    --awUI-marker-later: rgb(255, 0, 255);
    --awUI-marker-todo: rgb(255, 0, 255);
    --awUI-marker-now-doing: rgb(255, 0, 255);
    --awUI-marker-done: rgb(255, 0, 255);
}
```

**Expected behavior:**

I would expect all markers to be colored as magenta

**Screenshots**

Before triggering a change to the `custom.css`:
![image](https://user-images.githubusercontent.com/1262488/219656752-1198fd65-6759-433e-9324-50179fb5752f.png)

After triggering a change to the `custom.css`:
![image](https://user-images.githubusercontent.com/1262488/219656824-4555bfaf-7945-493f-a6b2-f86d9093f67f.png)

**Comment by yoyurec** [comment]
maybe it's about CSS loading order... try to add ` !important`
```css
:root {
    --awUI-marker-waiting: rgb(255, 0, 255) !important;
    --awUI-marker-later: rgb(255, 0, 255) !important;
    --awUI-marker-todo: rgb(255, 0, 255) !important;
    --awUI-marker-now-doing: rgb(255, 0, 255) !important;
    --awUI-marker-done: rgb(255, 0, 255) !important;
}
```

**Comment by yoyurec** [comment]
also suggestion - are editing in Logseq?
it works bad with custom.css! use external editor instead

**Comment by Zachu** [comment]
Can confirm, works with !important. Should that be added to the `README.md` also @yoyurec?

**Comment by yoyurec** [comment]
of course i will
