### ISSUE TITLE
Whenever I use cardstyle 'Awesome', serachbox are covered up by other cards

### ISSUE THREAD

**Issue by kmr0209** [yoyurec/logseq-awesome-ui#48]
**Info:**
- OS: Windows 11 home
- Logseq ver: 0.8.17
- Plugin ver: 1.7
- Theme name: Awesome UI

- [V] ⚠ Do i have issue with DISABLED my `custom.css`?

**Description:**
Whenever I use cardstyle 'Awesome', I cant use search reference in cards, because they are covered up by other cards

**To Reproduce:**
1. use card style Awesome
2. make two cards
3. try refrencing using (()) inside first card

**Expected behavior:**
 Searchbox is coverd up by next card.

**Screenshots**
![image](https://user-images.githubusercontent.com/119389432/219852410-03047560-1493-47ba-aecd-d848d1dc99de.png)

without Awesome Styler

![image](https://user-images.githubusercontent.com/119389432/219852441-37155bac-05d3-411d-afd1-8e8d499298bd.png)

with Awesome Styler
**Attach files**
Add (via drag-n-drop) .zip with `.md` files (if it needs) to help with bugfixind

**Comment by yoyurec** [comment]
fiexd!
