### ISSUE TITLE
Feature Request: Tags Plugin Support

### ISSUE THREAD

**Issue by eivanhoe** [yoyurec/logseq-awesome-ui#49]
Hello,

When you have spare time, I would like to request a Tags Plugin support. There is currently a CSS problem with Tags that makes the UI out of place. I have attached a screenshot of what it looks like.

Imgur Link:
[Screenshot](https://i.imgur.com/NUEIeN5.png)

Tags plugin:
https://github.com/gidongkwon/logseq-plugin-tags

Thank you!

**Comment by yoyurec** [comment]
fixed )
