### ISSUE TITLE
How to turn off the promotion notification?

### ISSUE THREAD

**Issue by feigaoxyz** [yoyurec/logseq-awesome-ui#5]
<img width="384" alt="2022-10-14-125928-CleanShot-eTBY5uM3" src="https://user-images.githubusercontent.com/5907519/195765911-734d9c5d-fb23-4bb0-9bbe-5125509a87a6.png">

**Comment by yoyurec** [comment]
it was done temporary after big plugin splitting to 4 to inform users who havn't seen Discord announce. will be deleted in next release in few days

**Comment by yoyurec** [comment]
deleted!
