### ISSUE TITLE
Keeping the default tab look 

### ISSUE THREAD

**Issue by wise-east** [yoyurec/logseq-awesome-ui#50]
Thank you for the great plugin! 

**Idea**
I like everything about this plugin but I'm not a fan of the brower-like tab look and would like to keep the default tab look from the tab plugin. 

**Screenshots**
the default look for reference: 
<img width="696" alt="Screen Shot 2023-02-24 at 5 59 45 PM" src="https://user-images.githubusercontent.com/31977186/221330048-f44dee00-1583-48d1-aee3-5d966c42f23c.png">

It would be great to be able to toggle this feature!

**Comment by yoyurec** [comment]
yes, will make it optional someday )
maybe soon...

**Comment by yoyurec** [comment]
done!
