### ISSUE TITLE
Even if the settings have been made, the right toolbar will still automatically hide.

### ISSUE THREAD

**Issue by moulai** [yoyurec/logseq-awesome-ui#53]
**Info:**
- OS: macOS 13.2 (22D49)
- Logseq ver: v0.8.18
- Plugin ver: v2.0.6
- Theme name: Awesome Styler Solarized default

- [x] ⚠ Do i have issue with DISABLED my `custom.css`?

**Description:**
Even if the settings have been made, the right toolbar will still automatically hide.
When the 'Hide right toolbar' option is unchecked in the plugin settings, the right toolbar will appear. However, after restarting Logseq, the right toolbar will be automatically hidden again.

**To Reproduce:**
1. Install the plugin.
2. Uncheck "Hide right toolbar" in the plugin settings.
3. Restart Logseq.
4. The right toolbar is still automatically hidden.

**Expected behavior:**
 After restarting Logseq, the toolbar on the right should be displayed, like the screenshot below. However, please note that there is no 'Page Map' option in the screenshot below, which is also a bug.
<img width="655" alt="image" src="https://user-images.githubusercontent.com/8275836/223518135-99ec6ff6-0593-4a59-bba2-9c63c87b1d07.png">

**Screenshots**
<img width="1327" alt="image" src="https://user-images.githubusercontent.com/8275836/223516709-77fc76c6-4c99-4450-8332-f3fcd6f66c3b.png">

**Attach files**
Add (via drag-n-drop) .zip with `.md` files (if it needs) to help with bugfixind

**Comment by yoyurec** [comment]
tnx!
fixed!
