### ISSUE TITLE
The “Toggle left menu” button in the top left corner is displaying incorrectly.

### ISSUE THREAD

**Issue by moulai** [yoyurec/logseq-awesome-ui#54]
**Info:**
- OS: macOS 13.2 (22D49)
- Logseq ver: v0.8.18
- Plugin ver: v2.0.6
- Theme name: Awesome Styler Solarized default

- [x] ⚠ Do i have issue with DISABLED my `custom.css`?

**Description:**
After enabling the plugin, the position of "Toggle left menu" in the upper left corner is very strange and partially obscured.

**Expected behavior:**
 The 'Toggle left menu' should be in a suitable position and should not be obstructed.
<img width="559" alt="image" src="https://user-images.githubusercontent.com/8275836/223519107-6f840f7b-5918-4183-ae4a-63297c7a22ac.png">

**Screenshots**
<img width="533" alt="image" src="https://user-images.githubusercontent.com/8275836/223519563-33806028-bab0-404b-9229-25456a11bc12.png">

**Attach files**
Add (via drag-n-drop) .zip with `.md` files (if it needs) to help with bugfixind

**Comment by stefanovolponi** [comment]
Also affected!

**Comment by yoyurec** [comment]
yes, known bug, figuring out....

**Comment by yoyurec** [comment]
fixed!
