### ISSUE TITLE
CSS issue when rendering on Ubuntu 22.10

### ISSUE THREAD

**Issue by rdevriese** [yoyurec/logseq-awesome-ui#55]
UI is not rendered correctly on Ubuntu 22.10. It looks fine on Windows 11. I've attached a screen shot of what I'm seeing.
![image](https://user-images.githubusercontent.com/9023077/223564013-d5a48103-5abc-4952-8fb0-dd447c92391e.png)

Using Awsome-UI V2.0.8

**Comment by yoyurec** [comment]
just fixed )
update to latest 2.0.9

**Comment by rdevriese** [comment]
Wow, that was freaky fast. It's working correctly now. Thanks.

**Comment by yoyurec** [comment]
actually i've tried to fix this fkng bug all day ))
