### ISSUE TITLE
Conflicts with the Text Wrapper  plugins

### ISSUE THREAD

**Issue by EasonSpirit** [yoyurec/logseq-awesome-ui#56]
**Info:**
- OS: windows 11
- Logseq ver: latest
- Plugin ver: latest
- Theme name: default

- [ ] ⚠ Do i have issue with DISABLED my `custom.css`?

**Description:**
A clear and concise description of what the bug is......

open awesome-ui
![image](https://user-images.githubusercontent.com/10186210/223688820-354b92e8-48a3-4be2-9f2c-17c8b84ffe45.png)
close awesome-ui
![image](https://user-images.githubusercontent.com/10186210/223688938-2f752cd9-f33a-4655-9f8c-4d976b716be3.png)

in  version  v1.8.2 there is no this problem
**To Reproduce:**
 ...

**Expected behavior:**
 ...

**Screenshots**

**Attach files**
Add (via drag-n-drop) .zip with `.md` files (if it needs) to help with bugfixind

**Comment by yoyurec** [comment]
fixed!

**Comment by EasonSpirit** [comment]
I update to the lastest version, but it dosen‘t work 😕

**Comment by yoyurec** [comment]
now should work, try latest

**Comment by EasonSpirit** [comment]
it works, thx!

**Comment by yoyurec** [comment]
cool!
