### ISSUE TITLE
Could you support mobile platforms?

### ISSUE THREAD

**Issue by ThreeIce** [yoyurec/logseq-awesome-ui#57]
**Idea**
As custom js and custom css are available on mobile platforms, I think there may be a way to use this cool theme on it although it may be complicated.

**Comment by yoyurec** [comment]
AwesomeUI mostly does desktop re-layouting. With lot of JS. with collab with others plugins (Agenda, Tabs).
UI on mobile totally different from desktop. Plugins not available. So which part of Awesome UI you are expecting to see on mobile?
I suggest:
* there are some styles left and not transferred yet to "Awesome Content" (have you tried it?) plugin (which is mobile-ready), such as page bottom icons (linked/unlinked/hierarchy)... Point me to these items and i will
* OR you are confused and talking about Awsome Styler? ))

**Comment by ThreeIce** [comment]
Sorry I didn't know that Awesome Content is mobile-ready as I'm confused about what each module is for. I just then fell in love with it and wanted to try it on mobile.

**Comment by ThreeIce** [comment]
I think I would like to have a full experience on my computer and when I switched to my mobile devices, some basic style would apply.

**Comment by yoyurec** [comment]
https://github.com/yoyurec/logseq-awesome-content#css-for-mobile-app

**Comment by yoyurec** [comment]
that's why "content related" stuff were moved to own plugin - to be without UI stuff, which is not needed and not applied on mobile

**Comment by ThreeIce** [comment]
If I set a special icon for a property, does it show on mobile device?

**Comment by yoyurec** [comment]
icon? isn't icons is an "Awesome Props" plugin? )) which is not ready (yet) for mobile?
https://github.com/yoyurec/logseq-awesome-props/issues/15

**Comment by ThreeIce** [comment]
Is there a prospect that by using custom.js, the theme setting set on the computer can also apply to the mobile devices like icons in awesome props?

**Comment by yoyurec** [comment]
continue in own repo plz https://github.com/yoyurec/logseq-awesome-props/issues/new/choose

**Comment by ThreeIce** [comment]
I mean that not only icons, but also styles set in Awesome Styler and etc can apply to the mobile
