### ISSUE TITLE
Add option to hide help-button

### ISSUE THREAD

**Issue by garderobier** [yoyurec/logseq-awesome-ui#58]
**Idea**
Perhaps it would be beneficial to hide the help button from the user interface, because after a while it no longer provides any added value to the user.

**Screenshots**
<img width="874" alt="grafik" src="https://user-images.githubusercontent.com/101436860/224583863-f0dcc0af-b2e0-41b2-b7e3-fa1859d05773.png">

**Comment by yoyurec** [comment]
done!
