### ISSUE TITLE
Awesome UI plugin causing issues with Draw.io plugin

### ISSUE THREAD

**Issue by aforank** [yoyurec/logseq-awesome-ui#65]
**Info:**
- OS: Windows 11
- Logseq ver: logseq-drawio-plugin
- Plugin ver: 2.2.6
- Theme name: Draqula

**Description:**
Menu bar of draw.io disappears while using Awesome UI plugin enabled. 
Please check this issue to understand the root cause https://github.com/lee88688/logseq-drawio-plugin/issues/1#issuecomment-1576104772

**To Reproduce:**
 - Install logseq-drawio-plugin
 - Install Awesome UI plugin
 - Create a draw.io file
 - The Menu bar of Draw.io disappears. 

**Expected behavior:**
 - Both plugins should work without impacting each other

**Screenshots**
![image](https://github.com/yoyurec/logseq-awesome-ui/assets/19813442/25c88942-0c29-4bcc-9d5f-c162c6a1037a)

**Comment by yoyurec** [comment]
can't reproduce... i see all bars.. which one is disappeared?

does the bug still exist?

**Comment by aforank** [comment]
It works fine now. Thanks! Closing it.
