### ISSUE TITLE
toggle left/right menu button unclickable

### ISSUE THREAD

**Issue by constfold** [yoyurec/logseq-awesome-ui#66]
**Info:**
- OS: Windows 11
- Logseq ver: 0.9.9
- Plugin ver: 2.2.6
- Theme name: Awesome Styler Solarized default

- [x] ⚠ Do i have issue with DISABLED my `custom.css`?

**Description:**
Both "toggle left menu" and "toggle right menu" are unclickable with other buttons works fine. See screenshots.

**Expected behavior:**
 I should be able to click two buttons to enable/disable left or right menu.

**Screenshots**

![图片](https://github.com/yoyurec/logseq-awesome-ui/assets/65550294/c62aa551-9394-4afb-8570-a3eb84dc8874)
![图片](https://github.com/yoyurec/logseq-awesome-ui/assets/65550294/a9fd0cb4-1a9e-4d44-9845-6e79916518f9)
![图片](https://github.com/yoyurec/logseq-awesome-ui/assets/65550294/2f596caf-f9dc-4f60-8f6a-82f208d05903)
![图片](https://github.com/yoyurec/logseq-awesome-ui/assets/65550294/f06367bf-b4bb-46fe-9282-c30360538e03)

**Comment by zellyshu** [comment]
I am getting the same error with Logseq 0.9.9, Plugin ver 2.2.6, Windows 10.

**Comment by t0rsten** [comment]
> I am getting the same error with Logseq 0.9.9, Plugin ver 2.2.6, Windows 10.

Me too.

**Comment by dongtsi** [comment]
Same problem. I think this is because v0.9.9 hides the native title bar for windows/linux, resulting in the overlapping of buttons

**Comment by hokutonanto** [comment]
Same here.

**Comment by cnut1648** [comment]
I can confirm, this happens to me as well

**Comment by iBeACoder** [comment]
This is happening on my system as well.

**Comment by cnut1648** [comment]
As mentioned in #68, this I blieve is caused by this https://github.com/logseq/logseq/pull/9442 and I have to enable `use naive titlebar` option in the setting to get rid of this UI glitch

**Comment by yoyurec** [comment]
fixed!
