### ISSUE TITLE
problems when the native title bar is disabled

### ISSUE THREAD

**Issue by ZhaoGY-N** [yoyurec/logseq-awesome-ui#68]
**Info:**
- OS: windows10
- Logseq ver: v0.9.10
- Plugin ver: v2.2.6
- Theme name: Awesome Styler Solarized default

- [ ] ⚠ Do i have issue with DISABLED my `custom.css`?

**Description:**
when the native title bar is disabled,  the close, restore and minimize buttons disappeared. And the left bar button didn't work once the logseq window is restored, ever after it backto maximized state.

**To Reproduce:**
 disable the native title bar ang restart logseq

**Expected behavior:**
the close, restore and minimize button disappeared.

**Screenshots**
![Snipaste_2023-07-10_10-56-13](https://github.com/yoyurec/logseq-awesome-ui/assets/62810902/400d42ee-d4b6-4421-848d-7caaeea7f6c1)

There should have three buttons. When the awesome ui is disabled, it works fine.
![image](https://github.com/yoyurec/logseq-awesome-ui/assets/62810902/a5f0e098-f2ec-4a9c-9dc4-abc59d454e65)

it same the same problem in #66

**Comment by soraphis** [comment]
Actually you _can_ kinda click them, at least for me they seem to be moved down below the tab bar: 
![image](https://github.com/yoyurec/logseq-awesome-ui/assets/3066582/bf61d4dc-b822-42b0-b613-e13395e236e5)

but yeah, would be nice if fixed.

**Comment by codeRSH** [comment]
Either minimize/maximize/close buttons should be completely removed or they should appear.

Right now they are occupying the space but are not really visible this making the right sidebar toggle button 'floats' somewhere in middle rather than snapping to right side of screen .

**Comment by yoyurec** [comment]
fixed!
