### ISSUE TITLE
Page delete confirmation dialog hides Yes & Cancel buttons when decreasing width of the window

### ISSUE THREAD

**Issue by senntore** [yoyurec/logseq-awesome-ui#7]
**Info:**
- OS: Pop!_OS 22.04
- Logseq ver: 0.8.8
- Theme ver: Awesome Syler v3.0.3

**Description:**
Title

**To Reproduce:**
- Select the option to delete a page to show the confirmation dialog.
- Decrease the width of the application window & see the changes.

**Expected behavior:**
 See the screenshot of the default theme

**Screenshots**
Theme: Chocolate from the plugin
![Screenshot from 2022-10-16 14-39-40](https://user-images.githubusercontent.com/58325574/196027776-da06f75f-17b1-4036-9f26-40bdb475f54a.png)

Default theme:
![Screenshot from 2022-10-16 14-39-51](https://user-images.githubusercontent.com/58325574/196027853-a54435a9-b985-487f-a544-92727bf9bb84.png)

**Comment by yoyurec** [comment]
AwesomeUI or AweseomeStyler? )
![image](https://user-images.githubusercontent.com/137919/196036022-e92f0c04-24bd-40f2-a815-0660010f4bd1.png)

**Comment by yoyurec** [comment]
what about latest v3.1.0? issue still exist?

**Comment by senntore** [comment]
Ah yes, it's fixed in v3.1.0, I should've checked for update for plugin before creating the issue.
I'll close the issue.
