### ISSUE TITLE
Logseq gives an error if Agenda plugin is not installed

### ISSUE THREAD

**Issue by joselitosn** [yoyurec/logseq-awesome-ui#72]
**Info:**
- OS: Windows 11 Pro 22H2 (also tested on Windows 10)
- Logseq ver: 0.9.19
- Plugin ver: 2.3.3
- Theme name: Default Dark Theme

- Empty custom.css

**Description:**
After installing the plugin, clicking to create or open any page gives me an error:

> Error caught by UI!
> NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

The error only disappeared after installing the Agenda plugin.

**To Reproduce:**
New install of Logseq, install the plugin and try to create a new page. Logseq immediately gives an error an need to be reopened.

**Expected behavior:**
Opens the new page.

The [Installation section](https://github.com/yoyurec/logseq-awesome-ui#installation) should indicate in case the agenda plugin is required.

---

Also the image used to represent the plugin can cause some confusion, since it also shows content from a lot of other plugins that are needed to achieve the same look and feel.

**Comment by yoyurec** [comment]
> The [Installation section](https://github.com/yoyurec/logseq-awesome-ui#installation) should indicate in case the agenda plugin is required.

Agenda plugin in NOT required... there is checker "is Agenda installed".
I've updated checker, try new version

**Comment by joselitosn** [comment]
It's fixed.

Thank you. 😁

**Comment by vivekKodira** [comment]
I'm seeing this error now - has this issue regressed?
