### ISSUE TITLE
Whiteboards don't appear on macOS M1

### ISSUE THREAD

**Issue by AvijeetPrasad** [yoyurec/logseq-awesome-ui#78]
**Info:**
- OS: macOS 14.2 (Apple M1 Pro)
- Logseq ver: 0.10.1
- Plugin ver: Awesome UI 2.4.0
- Theme name: Awesome Styler Bear

- [x] ⚠ Do i have issue with DISABLED my `custom.css`?
Issue gets resolved if I turn off the plugin

**Description:**
Whiteboards appear empty when clicked. Issue only with my mac M1 chip, works fine on my mac with Intel chip. See this following issue: https://github.com/logseq/logseq/issues/10712

**To Reproduce:**
- Click on Whiteboard on the sidebar
- From the list of All whiteboards, click on one of the file
- Empty page appears!

**Expected behavior:**
 Should have all the drawings as expected.

**Screenshots**
![image](https://github.com/yoyurec/logseq-awesome-ui/assets/45669486/0b0953e6-072c-4ff9-8eca-2b8d85ff4a90)
![image](https://github.com/yoyurec/logseq-awesome-ui/assets/45669486/a070ceee-287f-4aee-81c9-15c0f099dbe2)

**Comment by rowsof** [comment]
Confirming the issue and presenting detailed problem/solution. Used Developer tools to find the problematic css, which appears to be this line:

.cp__sidebar-main-content>div {
    position: relative;
}

If I comment out the position:relative the whiteboard returns. Here's a screenshot showing the issue resolved:
<img width="1230" alt="image" src="https://github.com/yoyurec/logseq-awesome-ui/assets/138329522/5102ba46-5b56-4a30-878b-b99c77836c47">

**Comment by AvijeetPrasad** [comment]
@rowsof 

Were you able to fix this by adding something in the `custom.css` file? If so, can you please share?

**Comment by rowsof** [comment]
yeah, try:
.cp__sidebar-main-content>div { position: inherit !important; }

**Comment by AvijeetPrasad** [comment]
> yeah, try: .cp__sidebar-main-content>div { position: inherit !important; }

Works well. Thank you :)

**Comment by dhnm** [comment]
> yeah, try: .cp__sidebar-main-content>div { position: inherit !important; }

⬆️ breaks the toolbar on mobile. This should work better for now: 
```css
.cp__sidebar-main-content > div:has(.whiteboard-page) {
    position: inherit;
}
```
