### ISSUE TITLE
Search bar squeezed when reading pdf

### ISSUE THREAD

**Issue by cleanclothes-pi** [yoyurec/logseq-awesome-ui#8]
**Info:**
- OS: Mac 12.2.1
- Logseq ver: 0.8.8
- Theme ver: Awesome UI v1.2.12; Awesome Styler 3.1.0
- [ ] ⚠ Do i have issue with DISABLED my `custom.css`?  <=(I don't understand this question)

**Description:**
When open PDF reader, the search bar is squeezed very narrowly, making search results very hard to read. With other pinned icons on the toolbar, the search is entirely unreadable, and therefore unusable.

**To Reproduce:**
Open up any PDF file then activate the search bar. Pin other plugin icons, then repeat the steps.

**Expected behavior:**
The search bar expand as much as possible to fill up the available space on the right. The search should at least shows some words.

**Screenshots**

*With no other pinned plugin icons on the search bar*
<img width="1437" alt="Screen Shot 2022-10-18 at 14 39 22" src="https://user-images.githubusercontent.com/58788103/196517529-37ff207e-0b4d-43cb-84ce-13ca8a98d310.png">
<img width="1434" alt="Screen Shot 2022-10-18 at 14 39 28" src="https://user-images.githubusercontent.com/58788103/196517567-e1dabfe6-dda6-419c-94c1-faa96d7da63d.png">

*With multiple pinned plugin icons on the toolbar*
<img width="1432" alt="Screen Shot 2022-10-18 at 14 24 05" src="https://user-images.githubusercontent.com/58788103/196517882-fa7d4f4a-b524-434f-a10b-42d8669ee35e.png">
<img width="1433" alt="Screen Shot 2022-10-18 at 14 24 13" src="https://user-images.githubusercontent.com/58788103/196517899-c9636101-6c94-4f56-91b4-4db0b3b17005.png">

**Comment by Horinne** [comment]
Same question.Can you add a option to turn off Search panel in the settings.

**Comment by yoyurec** [comment]
What about extend header, so there is jumps on PDF open + big search as before + all icons accessible?

![image](https://user-images.githubusercontent.com/137919/196858443-84392345-1ccc-4f66-8386-c59d484c4db1.png)

**Comment by cleanclothes-pi** [comment]
Personally I don't like that approach. Although it looks more consistent for sure, I think takes up too much from the reading area, and the PDF reader's UI pushed even further down. Some PDFs also have longer content per page, and will feel cramped.

**Comment by yoyurec** [comment]
agree. then will think another solution...

**Comment by yoyurec** [comment]
Update **v1.3.11**!

when PDF is opened:
* layout for reading maximized
* search popup size/position tuned

![image](https://user-images.githubusercontent.com/137919/198791932-4772dfa9-a4da-4548-8850-652ee205100c.png)

**Comment by yoyurec** [comment]
> Can you add a option to turn off Search panel in the settings

@Horinne done!
check latest **v1.6.x**

![search](https://user-images.githubusercontent.com/137919/217100628-d8eb30c6-a19e-480f-b7a4-5c24f02f1af8.png)
