### ISSUE TITLE
Property icon misalignment for multi-line values

### ISSUE THREAD

**Issue by cleanclothes-pi** [yoyurec/logseq-awesome-ui#9]
**Info:**
- OS: Mac
- Logseq ver: 0.8.9
- Plugin ver: 1.3.2
- Theme name: Awesome Styler

**Description:**
The icon of property misaligns with the property name when the value has mutiple line when opened on the right sidebar. The icon appears on bottom right corner. In some cases, another icon is created at the last line. (See the case of "tags" showing both a predefined icon and a new generic icon.)

**To Reproduce:**
Create a page with long prorperty value, such as page with metadata from zotero imports. Open this page on the right sidebar.

**Expected behavior:**
The property icons align with the property name. No duplicate icon.

**Screenshots**

<img width="485" alt="Screen Shot 2022-10-22 at 10 05 27" src="https://user-images.githubusercontent.com/58788103/197344151-6f2e8405-4887-49d3-98d9-2bf25ca33dd8.png">

**Comment by yoyurec** [comment]
fixed

**Comment by yoyurec** [comment]
oh! new uniconized props )) moment...

**Comment by yoyurec** [comment]
done!
![image](https://user-images.githubusercontent.com/137919/197347877-6410b472-5114-4cc8-805b-5b809a76a2f4.png)

PS: `isbn` is missed, will add in next update

**Comment by cleanclothes-pi** [comment]
Fantastic! Thank you!
